// Test for exceptions. Uncommenting any of the below should have an exception

//let r1 : int = array_bound1(0)
//let r2 : int = array_bound2(0)
//let r3 : int = 110/0
//let r4 : int = null(0)
//let r5 : int = a[2]
//let r6 : int = null2(a)
let a : array 1 = array[10]

function array_bound1 (x : int) : int {
  let y : array 1 = array [10]
  x := y[10]
  return x
}

function array_bound2 (x : int) : int {
  let y : array 1 = array [10]
  y[10] := x
  return x
}

function null (x : int) : int {
  let r5 : int = a[0]
  let a : array 1 = array[10]
  return x
}

function null2 (x : array 1) : int {
  let i : int = x[0]
  return i
}
